---
- name: Restart rootless docker
  become: true
  become_user: "{{ docker_user }}"
  ansible.builtin.systemd:
    name: docker.service
    state: restarted
    scope: user
  when:
    - docker_service_restart
